# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ASDFG' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ASDFG
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'PKHUD'
  pod 'ImageSlideshow/Kingfisher'
  pod 'RealmSwift'


  target 'ASDFGTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ASDFGUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
